WITH RECURSIVE R AS (
  WITH RECURSIVE N AS (
    SELECT 1 AS NUM
    UNION
    SELECT NUM + 1 FROM N WHERE NUM + 1 < 1000
  )
  SELECT A.NUM * B.NUM AS NUM, A.NUM * B.NUM AS TEMP
  FROM N AS A, N AS B
  UNION
  SELECT NUM, SUBSTR(TEMP, 2, LENGTH(TEMP) - 2)
  FROM R
  WHERE SUBSTR(TEMP, 1, 1) = SUBSTR(TEMP, -1, 1)
    AND LENGTH(TEMP) > 0
)
SELECT MAX(NUM) FROM R WHERE LENGTH(TEMP) = 0;
