-- SQLite で動作を確認
-- `sqlite3 -init ./problem.sql' で実行

-- 自然数のシーケンシャルなリスト
CREATE TABLE N(
  ID INTEGER PRIMARY KEY AUTOINCREMENT, 
  TMP
);

-- 倍々ゲームでレコード数を 1024 まで増やす
INSERT INTO N(TMP) VALUES (NULL);
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;
INSERT INTO N(TMP) SELECT ID FROM N;

-- 1000 未満の自然数のうち 3 か 5 の倍数になっている数の合計
SELECT SUM(ID)
FROM N
WHERE ID < 1000
  AND (ID % 3 = 0 OR ID % 5 = 0);
