-- SQLite で動作を確認
-- `sqlite3 < ./problem.sql' で実行

-- 自然数のシーケンシャルなリスト
CREATE TABLE N(
  NUM INTEGER PRIMARY KEY AUTOINCREMENT,
  DUMMY
);

-- 倍々ゲームでレコード数を 1024 まで増やす
INSERT INTO N(DUMMY) VALUES (NULL);
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;
INSERT INTO N(DUMMY) SELECT NUM FROM N;

-- 1000 未満の自然数のうち 3 か 5 の倍数になっている数の合計
SELECT SUM(NUM)
FROM N
WHERE NUM < 1000
  AND (NUM % 3 = 0 OR NUM % 5 = 0);
